In [219]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
%matplotlib inline

In [161]:
data = pd.read_csv('Telco_Customer_Churn.csv')

In [162]:
data.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [163]:
partner = pd.get_dummies(data['Partner'],prefix='partner',drop_first=True)
dependents = pd.get_dummies(data['Dependents'],prefix='Dependents',drop_first=True)
service = pd.get_dummies(data['PhoneService'],prefix='PhoneService',drop_first=True)
security = pd.get_dummies(data['OnlineSecurity'],prefix='OnlineSecurity',drop_first=True)
TechSupport = pd.get_dummies(data['TechSupport'],prefix='TechSupport',drop_first=True)
Contract = pd.get_dummies(data['Contract'],prefix='Contract',drop_first=True)
PaperlessBilling = pd.get_dummies(data['PaperlessBilling'],prefix='PaperlessBilling',drop_first=True)
Churn = pd.get_dummies(data['Churn'],prefix='Churn',drop_first=True)
gender = pd.get_dummies(data['gender'],prefix='gender',drop_first=True)
MultipleLines = pd.get_dummies(data['MultipleLines'],prefix='MultipleLines',drop_first=True)
Contract = pd.get_dummies(data['Contract'],prefix='Contract',drop_first=True)
PaymentMethod = pd.get_dummies(data['PaymentMethod'],prefix='PaymentMethod',drop_first=True)
InternetService = pd.get_dummies(data['InternetService'],prefix='InternetService',drop_first=True)
OnlineBackup = pd.get_dummies(data['OnlineBackup'],prefix='OnlineBackup',drop_first=True)

In [164]:
data.drop(['Partner','Dependents','PhoneService','OnlineSecurity','TechSupport','Contract','PaperlessBilling','Churn'],axis=1,inplace=True)

In [165]:
data

,gender,SeniorCitizen,tenure,MultipleLines,InternetService,OnlineBackup,DeviceProtection,StreamingTV,StreamingMovies,PaymentMethod,MonthlyCharges,TotalCharges
0,Female,0,1,No phone service,DSL,Yes,No,No,No,Electronic check,29.85,29.85
1,Male,0,34,No,DSL,No,Yes,No,No,Mailed check,56.95,1889.50
2,Male,0,2,No,DSL,Yes,No,No,No,Mailed check,53.85,108.15
3,Male,0,45,No phone service,DSL,No,Yes,No,No,Bank transfer (automatic),42.30,1840.75
4,Female,0,2,No,Fiber optic,No,No,No,No,Electronic check,70.70,151.65
...,...,...,...,...,...,...,...,...,...,...,...,...
7027,Male,0,24,Yes,DSL,No,Yes,Yes,Yes,Mailed check,84.80,1990.50
7028,Female,0,72,Yes,Fiber optic,Yes,Yes,Yes,Yes,Credit card (automatic),103.20,7362.90
7029,Female,0,11,No phone service,DSL,No,No,No,No,Electronic check,29.60,346.45
7030,Male,1,4,Yes,Fiber optic,No,No,No,No,Mailed check,74.40,306.60
7031,Male,0,66,No,Fiber optic,No,Yes,Yes,Yes,Bank transfer (automatic),105.65,6844.50

In [166]:
data.drop(['MultipleLines','InternetService','OnlineBackup','DeviceProtection','StreamingTV','StreamingMovies','PaymentMethod'],axis=1,inplace=True)

In [168]:
data

      SeniorCitizen  tenure  MonthlyCharges  TotalCharges
0                 0       1           29.85         29.85
1                 0      34           56.95       1889.50
2                 0       2           53.85        108.15
3                 0      45           42.30       1840.75
4                 0       2           70.70        151.65
...             ...     ...             ...           ...
7027              0      24           84.80       1990.50
7028              0      72          103.20       7362.90
7029              0      11           29.60        346.45
7030              1       4           74.40        306.60
7031              0      66          105.65       6844.50

[7032 rows x 4 columns]

In [169]:
data = pd.concat([data,partner,
dependents,
service,
security, 
TechSupport,
Contract,
PaperlessBilling,
Churn,
gender,
MultipleLines,
Contract,
PaymentMethod,InternetService,
OnlineBackup ],axis=1)

In [170]:
data

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,partner_Yes,Dependents_Yes,PhoneService_Yes,OnlineSecurity_No internet service,OnlineSecurity_Yes,TechSupport_No internet service,...,MultipleLines_Yes,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,InternetService_Fiber optic,InternetService_No,OnlineBackup_No internet service,OnlineBackup_Yes
0,0,1,29.85,29.85,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
1,0,34,56.95,1889.50,0,0,1,0,1,0,...,0,1,0,0,0,1,0,0,0,0
2,0,2,53.85,108.15,0,0,1,0,1,0,...,0,0,0,0,0,1,0,0,0,1
3,0,45,42.30,1840.75,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
4,0,2,70.70,151.65,0,0,1,0,0,0,...,0,0,0,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,0,24,84.80,1990.50,1,1,1,0,1,0,...,1,1,0,0,0,1,0,0,0,0
7028,0,72,103.20,7362.90,1,1,1,0,0,0,...,1,1,0,1,0,0,1,0,0,1
7029,0,11,29.60,346.45,1,1,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
7030,1,4,74.40,306.60,1,0,1,0,0,0,...,1,0,0,0,0,1,1,0,0,0
7031,0,66,105.65,6844.50,0,0,1,0,1,0,...,0,0,1,0,0,0,1,0,0,0

In [171]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [172]:
y = data['Churn_Yes']

In [173]:
X = data.drop('Churn_Yes',axis=1)

In [174]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

# Logistic Regression

In [176]:
from sklearn.linear_model import LogisticRegression
lm = LogisticRegression()
lm.fit(X_train,y_train)
predict = lm.predict(X_test)

C:\Users\Sadiq\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [177]:
from sklearn.metrics import classification_report

In [178]:
print('classification report LogisticRegression: \n', classification_report(y_test,predict))

classification report LogisticRegression:
               precision    recall  f1-score   support

           0       0.86      0.90      0.88      1580
           1       0.64      0.55      0.59       530

    accuracy                           0.81      2110
   macro avg       0.75      0.72      0.73      2110
weighted avg       0.80      0.81      0.80      2110

# Naive Bayes

In [180]:
from sklearn.naive_bayes import GaussianNB

In [181]:
gb = GaussianNB()

In [182]:
gb.fit(X_train,y_train)
predict = gb.predict(X_test)

In [183]:
print('classification report Naive Bayes: \n', classification_report(y_test,predict))

classification report Naive Bayes:
               precision    recall  f1-score   support

           0       0.91      0.65      0.76      1580
           1       0.44      0.80      0.57       530

    accuracy                           0.69      2110
   macro avg       0.67      0.73      0.66      2110
weighted avg       0.79      0.69      0.71      2110

# Decision Tree

In [185]:
from sklearn.tree import DecisionTreeClassifier

In [186]:
dfc = DecisionTreeClassifier(criterion='gini')

In [187]:
dfc.fit(X_train,y_train)
predict = dfc.predict(X_test)

In [188]:
print('classification report Decision Tree: \n', classification_report(y_test,predict))

classification report Decision Tree:
               precision    recall  f1-score   support

           0       0.83      0.78      0.81      1580
           1       0.45      0.53      0.49       530

    accuracy                           0.72      2110
   macro avg       0.64      0.66      0.65      2110
weighted avg       0.74      0.72      0.73      2110

# SVM

In [234]:
from sklearn.svm import SVC

In [200]:
svc.fit(X_train,y_train)

KeyboardInterrupt:

In [235]:
svc = SVC(kernel='linear',random_state=101)

In [236]:
predict = svc.predict(X_train)

NotFittedError: This SVC instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

# Random Forest

In [201]:
from sklearn.ensemble import RandomForestClassifier

In [202]:
rfc = RandomForestClassifier(random_state=101)

In [203]:
rfc.fit(X_train,y_train)

RandomForestClassifier(random_state=101)

In [204]:
predict = rfc.predict(X_test)

In [205]:
print('classification report Random Forest: \n', classification_report(y_test,predict))

classification report Random Forest:
               precision    recall  f1-score   support

           0       0.84      0.89      0.86      1580
           1       0.60      0.48      0.54       530

    accuracy                           0.79      2110
   macro avg       0.72      0.69      0.70      2110
weighted avg       0.78      0.79      0.78      2110

# KNN

In [211]:
from sklearn.neighbors import KNeighborsClassifier

In [212]:
nn = KNeighborsClassifier(n_neighbors=10)

In [213]:
nn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=10)

In [214]:
predict = nn.predict(X_test)

In [215]:
print('classification report KNeighborsClassifier: \n', classification_report(y_test,predict))

classification report KNeighborsClassifier:
               precision    recall  f1-score   support

           0       0.81      0.93      0.87      1580
           1       0.62      0.37      0.46       530

    accuracy                           0.79      2110
   macro avg       0.72      0.65      0.67      2110
weighted avg       0.77      0.79      0.77      2110

In [233]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

class_model = []

class_model.append(("Logistic Regression", LogisticRegression(solver='liblinear')))
class_model.append(("GaussianNB", GaussianNB()))
class_model.append(("DecisionTreeClassifier", DecisionTreeClassifier(criterion='gini')))
class_model.append(("RandomForestClassifier", RandomForestClassifier(n_estimators=100,criterion='gini')))
class_model.append(("KNeighborsClassifier", KNeighborsClassifier(n_neighbors=10)))

for name, model in class_model:
    kfold = KFold(n_splits=10,random_state=None)
    result = cross_val_score(model, X, y, cv=kfold, scoring='accuracy')
    print(result.mean())

0.8033272581792319
0.6980925901978534
0.7218422669080564
0.7918080386008018
0.7825657894736842